/**
 * Маппинг доп. полей МойСклад (name) → ключи JSON в колонке attributes.
 * scalar: long/time/boolean/string/double → value; customentity → value.name
 * split: «Категория ОЗ» — customentity.name режется по " // " → category, subcategory
 */
module.exports = [
  { kind: 'scalar', name: 'ID Bitrix', key: 'id_bitrix' },
  { kind: 'scalar', name: 'Акционная цена', key: 'price_promo' },
  { kind: 'scalar', name: 'Акционная цена (спец)', key: 'price_promo_special' },
  { kind: 'scalar', name: 'Акция выходного дня', key: 'weekend_promotion' },
  { kind: 'scalar', name: 'Большой ценник', key: 'large_tag' },
  { kind: 'scalar', name: 'Бренд', key: 'brand' },
  { kind: 'scalar', name: 'Витрина Европейский', key: 'showcase_eur' },
  { kind: 'scalar', name: 'Витрина КРД магазин', key: 'showcase_krd_store' },
  { kind: 'scalar', name: 'Витрина Мун', key: 'showcase_mun' },
  { kind: 'scalar', name: 'Витрина Новослободская', key: 'showcase_nov' },
  { kind: 'scalar', name: 'Витрина СПб', key: 'showcase_spb_store' },
  { kind: 'scalar', name: 'Витрина Таганская', key: 'showcase_tag' },
  { kind: 'scalar', name: 'Витрина Черемушки', key: 'showcase_cher' },
  { kind: 'scalar', name: 'Включение акции', key: 'promotion_activation' },
  { kind: 'scalar', name: 'Выводим', key: 'displayed' },
  { kind: 'scalar', name: 'Выключение акции', key: 'promotion_deactivation' },
  { kind: 'scalar', name: 'Высота (мм)', key: 'height' },
  { kind: 'scalar', name: 'Дата завершения акции', key: 'promotion_end_date' },
  { kind: 'scalar', name: 'Дата начала акции', key: 'promotion_start_date' },
  { kind: 'scalar', name: 'Дата поступления(ручная)', key: 'receipt_date_manual' },
  { kind: 'scalar', name: 'Дефицит', key: 'deficit' },
  { kind: 'scalar', name: 'Длина (мм)', key: 'length' },
  { kind: 'scalar', name: 'Длинная позиция', key: 'long_tail' },
  { kind: 'scalar', name: 'Зафиксировать цену офлайн', key: 'fix_price_offline' },
  { kind: 'split', name: 'Категория ОЗ', keys: ['category', 'subcategory'] },
  { kind: 'scalar', name: 'Категория филипс', key: 'category_philips' },
  { kind: 'scalar', name: 'Количество к заказу лимит позиции', key: 'order_limit_quantity' },
  { kind: 'scalar', name: 'Контрольная цена закупки (для скрипта)', key: 'price_control_purchase' },
  { kind: 'scalar', name: 'Контрольная цена продажи (для скрипта)', key: 'price_control_sale' },
  { kind: 'scalar', name: 'Маркетинговый товар, нулевая себестоимость', key: 'marketing_product_zero_cost' },
  { kind: 'scalar', name: 'матрица B2B', key: 'matrix_b2b' },
  { kind: 'scalar', name: 'Матрица выставки', key: 'matrix_exhibition' },
  { kind: 'scalar', name: 'матрица маркет-плейсы', key: 'matrix_marketplaces' },
  { kind: 'scalar', name: 'матрица онлайн', key: 'matrix_online' },
  { kind: 'scalar', name: 'матрица оффлайн', key: 'matrix_offline' },
  { kind: 'scalar', name: 'Место хранения', key: 'storage_location' },
  { kind: 'scalar', name: 'Месяц предзаказа', key: 'preorder_month' },
  { kind: 'scalar', name: 'Минимальная наценка (%)', key: 'min_markup' },
  { kind: 'scalar', name: 'Минимальная цена (расчетная)', key: 'price_min_calculated' },
  { kind: 'scalar', name: 'Минимальный запас Рижская', key: 'min_stock_rizh' },
  { kind: 'scalar', name: 'Минимальный запас СПб', key: 'min_stock_spb' },
  { kind: 'scalar', name: 'МРЦ ОПТ', key: 'mrc_opt' },
  { kind: 'scalar', name: 'Наценка ОПТ(%)', key: 'opt_markup' },
  { kind: 'scalar', name: 'Не отправлять остатки в Ozon', key: 'exclude_stocks_from_ozon' },
  { kind: 'scalar', name: 'Не отправлять остатки в Ozon ИП Кершковский', key: 'exclude_stocks_from_ozon_ip_kersh' },
  {
    kind: 'scalar',
    name: 'Не отправлять остатки и цены в OZON fbs ДокторСлон',
    key: 'exclude_stocks_prices_from_ozon_fbs_ds'
  },
  { kind: 'scalar', name: 'Не участвует в синхронизации с сайтом', key: 'exclude_from_site_sync' },
  { kind: 'scalar', name: 'Неснижаемый остаток Европейский', key: 'nz_eur' },
  { kind: 'scalar', name: 'Неснижаемый остаток КРД Магазин', key: 'nz_krd_store' },
  { kind: 'scalar', name: 'Неснижаемый остаток КРД опт', key: 'nz_krd_opt' },
  { kind: 'scalar', name: 'Неснижаемый остаток Мун', key: 'nz_stock_mun' },
  { kind: 'scalar', name: 'Неснижаемый остаток Новослободская', key: 'nz_stock_nov' },
  { kind: 'scalar', name: 'Неснижаемый остаток Рижская', key: 'nz_stock_rizh' },
  { kind: 'scalar', name: 'Неснижаемый остаток СПб', key: 'nz_stock_spb' },
  { kind: 'scalar', name: 'Неснижаемый остаток СПб Магазин', key: 'nz_stock_spb_store' },
  { kind: 'scalar', name: 'Неснижаемый остаток Таганская', key: 'nz_stock_tag' },
  { kind: 'scalar', name: 'Неснижаемый остаток Черемушки', key: 'nz_stock_cher' },
  { kind: 'scalar', name: 'Обновить в Битрикс', key: 'update_in_bitrix' },
  { kind: 'scalar', name: 'Отслеживание остатка подарка', key: 'track_gift_stock' },
  { kind: 'scalar', name: 'Первый день акции', key: 'promotion_first_day' },
  { kind: 'scalar', name: 'Порог изменения цены(%)', key: 'price_change_threshold' },
  { kind: 'scalar', name: 'Последний день акции', key: 'promotion_last_day' },
  { kind: 'scalar', name: 'Признак СТМ', key: 'sign_stm' },
  { kind: 'scalar', name: 'Приоритет', key: 'priority' },
  { kind: 'scalar', name: 'Приоритетная матрица', key: 'priority_matrix' },
  { kind: 'scalar', name: 'Сегмент ABC', key: 'abc_segment' },
  { kind: 'scalar', name: 'Скидка без ограничений', key: 'unlimited_discount' },
  { kind: 'scalar', name: 'Скрыть в Купер Мск', key: 'hide_in_kuper_msk' },
  { kind: 'scalar', name: 'Скрыть в Купер СПб', key: 'hide_in_kuper_spb' },
  { kind: 'scalar', name: 'Скрыть в мегамаркет', key: 'hide_in_megamarket' },
  { kind: 'scalar', name: 'Скрыть в Яндекс FBS', key: 'hide_in_yandex_fbs' },
  { kind: 'scalar', name: 'Скрыть в Яндекс FBY / FBY+', key: 'hide_in_yandex_fby' },
  { kind: 'scalar', name: 'Скрыть в Яндекс Go Мск', key: 'hide_in_yandex_go_msk' },
  { kind: 'scalar', name: 'Скрыть в Яндекс Go СПб', key: 'hide_in_yandex_go_spb' },
  { kind: 'scalar', name: 'Скрыть на сайте', key: 'hide_on_site' },
  { kind: 'scalar', name: 'Старая цена', key: 'price_old' },
  { kind: 'scalar', name: 'Статус МП', key: 'marketplace_status' },
  { kind: 'scalar', name: 'Товар КЗ', key: 'kz_product' },
  { kind: 'scalar', name: 'Товар МП', key: 'mp_product' },
  { kind: 'scalar', name: 'Товар не участвует в перемещениях СПб', key: 'exclude_from_transfers_spb' },
  { kind: 'scalar', name: 'Товар под заказ', key: 'made_to_order' },
  { kind: 'scalar', name: 'Упаковка МП', key: 'marketplace_packaging' },
  { kind: 'scalar', name: 'Участвует в акции', key: 'participates_in_promotion' },
  { kind: 'scalar', name: 'Участвует в наборах', key: 'participates_in_bundles' },
  { kind: 'scalar', name: 'Цена для маркета', key: 'price_market' },
  { kind: 'scalar', name: 'Цена продажи (сохраненная)', key: 'price_sale_saved' },
  { kind: 'scalar', name: 'Ширина (мм)', key: 'width' }
];
